version: 0.0
os: linux

files:
  - source: /website.zip               # The ZIP file created by CodeBuild
    destination: /tmp/website.zip       # This is where CodeDeploy will place the ZIP file on the EC2 instance

hooks:
  BeforeInstall:
    - location: /tmp/scripts/install_nginx.sh    # Correct path after extraction
      timeout: 300
      runas: root

  AfterInstall:
    - location: /tmp/scripts/unzip_website.sh    # Correct path after extraction
      timeout: 180
      runas: root

  ApplicationStart:
    - location: /tmp/scripts/start_nginx.sh      # Correct path after extraction
      timeout: 180
      runas: root
