version: 1.0

phases:
  install:
    commands:
      - echo "Installing updates and NGINX..."
      - apt-get update -y
      - apt-get install nginx zip -y

  pre_build:
    commands:
      - echo "Preparing build directory..."
      - mkdir -p build_output

  build:
    commands:
      - echo "Copying site files to build_output directory..."
      - cp -r about.html contact.html index.html portfolio.html price.html service.html css js img vendor build_output/

  post_build:
    commands:
      - echo "Creating ZIP artifact..."
      - cd build_output
      - zip -r ../website.zip .
      - cd ..
      - echo "Build and ZIP complete."

artifacts:
  files:
    - '**/*'

